name: Push

on:
  push:
    branches:
      - main  # Puedes especificar la rama en la que se ejecutará el action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ORG_DOCKER_USERNAME }}
        password: ${{ secrets.ORG_DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: mundosegrupo9/shopping-cart:pushAction01

    - name: Post image digest
      run: echo ${{ steps.build-and-push.outputs.digest }}
